= Interview
:docinfo:
Community and Dmitry Rakovets
:sectnums:
:toc: left
:toclevels: 1
:figure-caption!:

== О ресурсе

Большое количество времени при подготовке к интервью отнимает поиск вопросов, тестовых заданий и практических задач, с помощью которых, можно подготовиться к интервью. Существует огромное количество ресурсов в сети интернет, но материал, который они содержат, либо не полный, либо не актуальный.

* Ресурс содержит необходимые материалы, для того что ускорить и упростить вашу подготовку к интервью.
* Материал, в большинстве своем, основывается на реальных заданиях, задачах и вопросах, которые использовались на интервью.
* Материал агрегирован при участии сообщества. За что мы можем выразить всем участникам *огромную благодарность*!)

== Как поддержать?

*Обязательно подписывайтесь* на следующие социальные сети, вам не сложно, а меня это *будет мотивировать* заниматься развитием инструментов, который сделают жизнь начинающих разработчиков, и не только, намного *проще и комфортнее*.

* *Канал на YouTube*: link:https://www.youtube.com/c/DmitryRakovets[Dmitry Rakovets]
* *Группа в Telegram*: link:https://t.me/rakovets_group[Java :: group]
* *Канал в Telegram*: link:https://t.me/rakovets_channel[Java :: channel]

== Как помочь?

NOTE: *Если вы видите ошибки в тексте* или какие-то несостыковки, пожалуйста, сообщайте в группу в link:https://t.me/rakovets_group[Telegram] - это позволит сделать контент еще более качественным.

NOTE: *Вы можете предложить свои задачи, вопросы или другой материал*, который стоит добавить. Так же *вы можете предложить свои улучшения* текущей структуры или контента. Ваши идеи сообщайте в группу в link:https://t.me/rakovets_group[Telegram] - это позволит сделать контент еще более полезным и насыщенным.

== Как проходит интервью?

WARNING: Этапы интервью очень сильно разнятся от компании к компании. Иногда техническое интервью может проходить дважды, у самой компании и у клиента этой компании.

Возможные *этапы интервью*:

* *Предварительный отбор с помощью тестового задания*
* *Предварительный отбор с помощью HR-специалиста*
* *Интервью с техническим специалистом*. Каждый специалист выбирает свой подход к такому интервью. Наиболее частые подходы
** *Вопрос-ответ*
** *Решение алгоритмических задач*
** *Разговор о вашем опыте* (обычно с уточняющими вопросами)
** *Проверка на умение думать*: ставится задача, которую требуется решить, кандидат пытается ее решить, детально описывая что он делает (в процессе  обычно можно задавать уточняющие вопросы)
* *FIT-интервью* в команду.

== Тестовые задания

*Задания*, в большинстве своем, представляют собой примеры, которые предлагают различные компании в качестве *практического тестового задания* для того, что бы отобрать специалистов на работу, стажировку или обучение

link:./test-tasks[Тестовые задания]

== Практические задачи

*Задачи*, которые предлагают различные компании в качестве *практических задач* в процессе проведения технического интервью (т.е. вы их решаете и при этом шарите свой экран).

link:tasks[Практические задачи]

== Вопросы

*Вопросы*, которые задают специалисты на техническом интервью.

link:./questions/[Вопросы]

== Вопросы с ответами

link:./questions-answers/[Вопросы с ответами]
