= Тестовое задание 6

Создать простое веб-приложение, функционал которого включает следующее:

* Начальная страница
* Регистрация
* Авторизация
* Главная страница

*Сценарий*:

* Пользователь попадает на начальную страницу, на которой есть два поля для ввода текста (E-mail и Пароль) и две кнопки (Войти и Регистрация).
* Введя e-mail и пароль, и нажав на кнопку "Войти" отправляется запрос на сервер, где происходит проверка на наличие аккаунта пользователя в системе.
* Если данные корректны, происходит переход на Главную страницу, на которой указаны e-mail и статус аккаунта (Подтвержден/Не подтвержден) и есть кнопка "Выход".
* Введя e-mail и пароль, и нажав на кнопку "Регистрация" отправляется запрос на регистрацию. Если аккаунта пользователя нет в системе, то создается новый аккаунт, на указанную почту отправляется письмо, в тексте которого будет ссылка для подтверждения, а пользователь попадает на Главную страницу.

*Условия*:

* Использовать фреймворк Play https://www.playframework.com/
* Не использовать готовые решения
* Обработать ошибки
* Если возникают вопросы, не бояться спрашивать у других разработчиков
