= Тестовое задание 4

Для решения этого задания требуется от 12 до 48 рабочих часов. Это не значит, что вы решите ее за 12-48 часов. Можно потратить столько часов, сколько вы считаете нужным.

Мы предлагаем вам потратить хотя бы несколько часов на чтение задачи и моделирование решения. Мы протестировали эту задачу на наших инженерах: несколько младших разработчиков в среднем тратили 10 часов на чтение и размышления и примерно 2 часа на программирование.

*Прикладная теория музыки*

В теории музыки *интервал* — это расстояние между двумя *нотами*. Это расстояние указывается с помощью _буквы_ и _числа_. Например, допустимые названия интервалов - `M3`, `P5` или `m7`. _Буква_ и _цифра_ в названии интервала означают определенные вещи.

Как и в математике, если мы говорим, что расстояние на сантиметровой линейке между `3` и `5` равно `2` сантиметрам, в музыке мы говорим, что расстояние между `C` и `E` (или `do` и `mi`) равно `M3`.

Для этой задачи мы используем следующие имена *нот*:
`C` `D` `E` `F` `G` `A` `B`

Весь список *интервалов*, которые мы используем в этой задаче:
`m2`, `M2`, `m3`, `M3`, `P4`, `P5`, `m6`, `M6`, `m7`, `M7`, `P8`

____
Нотный стан (Нотоносец) в музыкальной нотации — набор параллельных горизонтальных линий (нотных линеек), на которых (и между которыми)записываются ноты.
____

*Номер интервала* — это количество *названий букв* или *позиций нотного стана* (строк и пробелов), которые он содержит, *включая позиции обеих нот*, образующих *интервал*. Например, интервал `C` – `G` является пятым (обозначается `P5`), потому что ноты от `C` до `G` над ним содержат пять буквенных имен (`C`, `D`, `E`, `F`, `G`) и занимают пять последовательных _позиций нотного стана_, включая _позиции_ of `C` и `G`. _Интервал_ от `A` до `A` содержит `8` _нот_ (`A` `B` `C` `D` `E` `F` `G` `A`) и называется `P8`. Мы будем называть это число *диатонической степенью* (обратите внимание: термин «степень», который мы здесь используем, может не соответствовать фактическому термину в музыке).

Единица расстояния между нотами называется *полутоном*.

Названия букв могут быть изменены случайно. *Диез* `#` поднимает ноту на полтона, а *бемоль* `b`** опускает его на полтона. К ноте можно добавить не более `#` и двух `b`.

В следующей таблице показаны 12 нот *хроматической гаммы*, построенной на `C`. Расстояние между каждой *нотой* в таблице составляет *полутон*. Обратите внимание, что одну и ту же *ноту* можно описать разными буквами. Например, если мы поднимем `C` на полутон, мы получим `C#`. А если понизить `D` на полутон, мы получим `Db`.

`C` `C#`/`Db` `D` `D#`/`Eb` `E` `F` `F#`/`Gb` `G` `G#`/`Ab` `A` `A#`/`Bb` `B`

Например, расстояние в `4` _полутона_ между `C` и `E`, расстояние в `5` _полутонов_ между `D` и `G` и расстояние в `1` _полутон_ между `Bb` и `B`.

____

*Знаки альтерации*:

* *sharp*/**диез** `#`
* *flat*/**бемоль** `b`
* *natural*/**бекар** `♮`

____

Если мы добавим какие-либо *знаки альтерации* к нотам, образующим *интервал*, по определению *ноты* не меняют своей *степени*. Как следствие, любой *интервал* имеет тот же номер *интервала*, что и соответствующий естественный интервал (означает интервал, образованный теми же нотами, без *знаки альтерации*). Например, интервалы `C` – `G#` (охватывающие `8` _полутонов_) и `C#` – `G` (охватывающие `6` полутонов) являются `P5`, как соответствующий естественный интервал `C` – `G` (`7` _полутонов_).

Обратите внимание, что *числа интервалов* представляют собой количество содержащихся *степеней* или *имен нот*, включая их, но не разницу между конечными точками. Другими словами, вы считаете _первую ноту за 1, а не за 0_. По этой логике интервал `C` – `D` является вторым (`M2`), но `D` находится только на одну степень выше `C`. Аналогично, `C` – `E` является третьим (`M3`), но `E` всего на две степени выше `C`, и так далее.

Мы будем _использовать только интервалы до октавы_ (`P8`, `12` _полутонов_).

Чтобы построить _интервал_ из данной _ноты_, вам сначала нужно найти *диатонический степень* ноты ниже или выше данной ноты.

Затем вам нужно отсчитать количество _полутонов_ от _начальной ноты_. В последовательности `C` `D` `E` `F` `G` `A` `B` есть один полутон между `E` и `F` и `B` и `C`. Между другими нотами есть два полутона.

Здесь один дефис означает один полутон:

`C--D--E-F--G--A--B-C`

== Как подсчитать количество полутонов?

. Давайте посчитаем количество полутонов между `C` и `G`: от `C` до `D` - `2` полутона, от `D` до `E` - `2` полутона, от `E` до `F` - `1` полутон, от `F` до `G` - `2` полутона. `2 + 2 + 1 + 2 = 7` полутонов.
. Давайте найдем количество полутонов между `A` и `C`: от `A` до `B` - `2` полутона, от `B` до `C` - `1` полутон. `2 + 1 = 3` полутона.

== Как подсчитать количество интервалов?

. Давайте найдем наш первый интервал - `P5` (**perfect fifth**) от `Ab`. `P5` означает: найти расстояние в `5` степеней и `7` полутонов.
* Сначала найдите `5`-ю степень от `A`, игнорируя `b`: (`A` `B` `C` `D` `E`) - `E` - это нота `5`-й степени от `A`.
* Теперь посчитайте полутоны: от `Ab` до `B` - `3` полутона (от `Ab` до `A` - `1` полутон, от `A` до `B` - `2` полутона), от `B` до `C` - `1` полутон, от `C` до `D` - `2` полутона, от `D` до `E` - `2` полутона. `3 + 1 + 2 + 2 = 8` полутонов. Это слишком много, нам нужно всего `7` полутонов, но нам нужно оставаться на `E`. Для этого понизьте `E` на один полутон, используя *знак альтерации* `b`.
* На расстоянии `P5` от `Ab` находится нота `Eb`.
* Примечание: вы не можете написать `D#` в качестве ответа, потому что даже если `D#` составляет `7` полутонов от `Ab`, он имеет другую степень (он находится всего на `4` степени от `A` до `D`).

== Пример

. Чтобы показать вам, как работать со *знаками альтерации*, давайте найдем `P5` (`5`-я ступень, `7` полутонов) из `A#`:
* Как и в предыдущем примере, найдите `5`-ю ступень из `A`, игнорируя `#`: (`A` `B` `C` `D` `E`) - `E` - пятая нота из `A` (и из `A#`).
* Теперь посчитаем полутоны: от `A#` до `B`- `1` полутон, от `B` до `C` - `1` полутон, от `C` до `D` - `2`полутона, от `D` до `E` - `2` полутона. `1 + 1 + 2 + 2 = 6` полутонов. Нам нужно добавить всего один полутон, добавив `#`: `E#`
* На расстоянии `P5` от `A#` находится нота `E#`.

== Пример

. Давайте найдем `m2` (`2`-я степень, `1` полутон) от `Fb`:
* Найти вторую ступень легко: (`F` `G`) - `G` - вторая нота от `F`.
* Теперь посчитаем полутоны: от `Fb` до `G` - `3` полутона. Это слишком много, нам нужен только один. Итак, мы должны понизить `G` на `2` полутона. Для этого добавьте к ноте `G` два `b`: `Gbb`.
* На расстоянии `m2` от `Fb` находится нота `Gbb`.

Названия интервалов, качество и количество

|===
|||полутон|степень
|`m2`|**Minor Second**|1|2
|`M2`|**Major Second**|2|2
|`m3`|**Minor Third**|3|3
|`M3`|**Major Third**|4|3
|`P4`|**Perfect Fourth**|5|4
|`P5`|**Perfect Fifth**|7|5
|`m6`|**Minor Sixth**|8|6
|`M6`|**Major Sixth**|9|6
|`m7`|**Minor Seventh**|10|7
|`M7`|**Major Seventh**|11|7
|`P8`|**Perfect Octave**|12|8
|===

Ваша задача реализовать две функции, которые будут работать с интервалами: одна будет строить интервал, а вторая определять интервал.

=== Требования:

==== intervalConstruction()

* Функция `intervalConstruction()` должна принимать массив строк в качестве входных данных и возвращать строку.
* Массив состоит из трех или двух элементов.
* Первый элемент в массиве — это имя интервала, второй — начальная нота, а третий указывает, идет ли интервал по возрастанию или по убыванию.
* Если в массиве нет третьего элемента, по умолчанию порядок построения возрастает.
* Функция должна вернуть строку, содержащую название заметки.
* В строке возврата разрешены только следующие имена заметок:

`Cbb Cb C C# C## Dbb Db D D# D## Ebb Eb E E# E## Fbb Fb F F# F## Gbb Gb G G# G## Abb Ab A A# A## Bbb Bb B B# B##`

* Если во входном массиве больше или меньше элементов, должно быть выдано исключение: `Illegal number of elements in input array`
* Соглашение: `['a', 'b']` здесь означает массив строк.

===== Примеры ввода и значение:

Обратите внимание: данные, которые получит ваша функция, будут выглядеть как массив строк, как определено на вашем языке. Никакого дополнительного разбора не требуется! Форма `['', '']` - это просто соглашение!

Допускаются следующие примечания:

`Cb C C# Db D D# Eb E E# Fb F F# Gb G G# Ab A A# Bb B B#`

Допускаются следующие интервалы ввода:

`m2 M2 m3 M3 P4 P5 m6 M6 m7 M7 P8`

`['M3','A','asc']` - построить возрастающий интервал M3, начиная с A
`['m7, 'Fb', 'dsc']` - построить убывающий интервал m7, начиная с Fb
`['P5', 'C']` - построить восходящий интервал P5, начиная с C
`['P4', 'E#]` - построить восходящий интервал P4, начиная с E #

==== intervalIdentification()

* Функция `intervalIdentification()` должна принимать в качестве входных данных массив строк и возвращать строку.
* Массив состоит из трех или двух элементов.
* Первый элемент - это первая нота в интервале, второй элемент - это последняя нота в интервале, третий указывает, идет ли интервал по возрастанию или по убыванию.
* Если в массиве нет третьего элемента, по умолчанию интервал считается возрастающим.
* Функция должна вернуть строку - название интервала.
* В строке возврата разрешены только следующие интервалы:

`m2 M2 m3 M3 P4 P5 m6 M6 m7 M7 P8`

* Если интервал не подходит под описание, должно быть выдано исключение: `Cannot identify the interval`.

Соглашение: `['a', 'b']` здесь означает массив строк.

===== Примеры ввода и значение:

Обратите внимание: данные, которые получит ваша функция, будут выглядеть как массив строк, как определено на вашем языке. Никакого дополнительного разбора не требуется! Форма `['', '']` - это просто соглашение!

Допускаются следующие примечания:

`Cbb Cb C C# C## Dbb Db D D# D## Ebb Eb E E# E## Fbb Fb F F# F## Gbb Gb G G# G## Abb Ab A A# A## Bbb Bb B B# B##`

`['C', 'D']` - найти возрастающий интервал между `C` и `D`
`['C#', 'Fb']` - найти возрастающий интервал между `C#` и `Fb`
`['A', 'G#', 'asc']` - найти возрастающий интервал между `A` и `G#`

Вы можете найти больше примеров здесь. Мы протестируем ваше решение на этом и подобных примерах.
