= Тестовое задание 18

Необходимо реализовать веб-приложение *Погодный брокер* (по принципу REST API).

== Что реализовать?

1. Ввод названия города. Форма заполняется и отправляется из *Postman* (https://www.postman.com/). Отправляется запрос (rest-метод) на link:weather.yahoo.com[] (или любой другой бесплатный погодный АPI) с введенным городом в качестве параметра. Форматы запросов детально описаны на сайте link:weather.yahoo.com[]. Полученный ответ посредством *Jackson* парсится в Java-класс, который далее с помощью *Spring JMS Template* отправляется в JMS-очередь, настроенную по архитектуре *Public-Subscriber*.

2. Необходимо реализовать *Spring JMS Listener*, получающий сообщения из созданной JMS-очереди. После получения, содержимое сообщения конвертируется и сохраняется в базу данных посредством *Hibernate*. Данная операция должна быть обернута в *Spring Transaction* (достаточно аннотации `@Transactional`).

3. Необходимо с помощью *Spring Web* реализовать REST-endpoint, который по определенному запросу, с указанием в качестве параметра названия города, будет возвращать _xml_ или *json* с соответствующей информацией о погоде. Информация берется из базы данных посредством *Hibernate*, парсится в _json_ или _xml_ с помощью *Jackson*.

== Технические требования

* Необходимо обеспечить покрытие исходного кода *unit*-тестами, с использованием *JUnit* и *Mockito*, или аналогов.
* Проект должен собираться сборщиком *maven* или *gradle*.
* Исходники нужно загрузить на *gitlab*. Сделать `gitlab-ci.yaml`, который запускает тесты и собирает проект.
* Программный код должен удовлетворять *Code Conventions*.
* JMS-брокер можно использовать любой (*Rabbit MQ*, *Kafka*, *Active MQ*).
* В качестве *СУБД* рекомендуется использовать *PostgreSQL* или *MySQL*.
* Архитектура приложения должна быть реализована максимально-несвязанной, с использованием принципа *Inversion of Control*.
* *СУБД*, *ЈМS-брокер* и пр. желательно развернуть с помощью *Docker Compose*.
