= Тестовое задание 17

*Задача*: спроектировать и разработать API для системы опросов пользователей.
*Использовать технологии*: Spring Framework.

== Функционал для администратора системы

* Авторизация в системе (регистрация не нужна)
* Добавление/изменение/удаление опросов. Атрибуты опроса: _название_, _дата старта_, _дата окончания_, _описание_. После создания поле _дата старта_ у опроса менять нельзя
* Добавление/изменение/удаление вопросов в опросе. Атрибуты вопросов: _текст вопроса_, _тип вопроса_ (_ответ текстом_, _ответ с выбором одного варианта_, _ответ с выбором нескольких вариантов_)

== Функционал для пользователей системы:

* Получение списка активных опросов
* Прохождение опроса: опросы можно проходить анонимно, в качестве идентификатора пользователя в API передаётся числовой ID, по которому сохраняются ответы пользователя на вопросы; один пользователь может участвовать в любом количестве опросов
* Получение пройденных пользователем опросов с детализацией по ответам (т.е. что выбрано), по ID  уникальному пользователя

== Результат выполнения задачи

* Исходный код приложения в github (только на github, публичный репозиторий)
* Инструкция по разворачиванию приложения (в docker или локально)
* Документация по АРІ
