= Тестовое задание 10

*Payment cards*

== Технологии

Java 11, Spring Boot, Spring Data, MySQL, Swagger UI

== Условие

Дано:

. Клиент
.. ФИО
.. Номер телефона
.. Email
.. Статус
. Платежная карта
.. Номер
.. Валюта
... BYN
... EUR
... USD
. Тип
.. Classic
.. Gold
.. Platinum

Необходимо реализовать REST сервис, который имеет:

1. Метод заведения клиента в системе.
2. Метод оформления карты и привязки к определенному клиенту (на основании выбранного типа карты, клиенту присваивается соответствующий статус: `Classic` – `0`, `Gold` – `1`, `Platinum` – `2`).
3. Метод, который возвращает постранично список номеров телефонов в зависимости от указанных параметров (количество записей, номер страницы, тип карты, валюта).

== Требования

1. Результат выполнения задания размещается на сервисе GitHub, ссылка на репозиторий отправляется рекрутеру для проверки задания.
2. Выполнять задание необходимо самостоятельно, без уточнения дополнительных деталей (как понимаем, так и делаем).
3. Нельзя использовать связи Hibernate (one to one, one to many, many to many).

== Будет плюсом

1. Организовать безопасный доступ к методам с помощью Spring Security (JWT, Basic Auth).
2. Покрытие методов тестами.
3. Для всех методов сделать описание для Swagger c помощью аннотаций.
