= Тестовое задание 15

== Описание

Существует некоторый бизнес-процесс – пополнение счета консультанта с помощью транзакций с
банковской карты в рублях.

Требуется реализовать сервисы 2 микросервиса.

=== Микросервис `Payment`

Должен иметь endpoint на получение `{host}/pay`. `POST` запроса с телом json в формате:

[source, json]
----
{
    "accountId": 1, // ID аккаунта консультанта
    "amount": 100.2 // Сумма пополнения в рублях
}
----

Endpoint сервиса должен получать, обрабатывать этот json и отправлять в некоторую очередь
`Queue` таких транзакций.

=== Микросервис `Backend`

- Должен читать очередь `Queue`
- Сохранять транзакции из очереди `Queue` в базу данных Postgres `payments`
- Каждые 5 минут записывать в файл `transaction.csv` в локальной папке транзакции в
формате

[source, csv]
----
id;account_id;amount;datetime_transaction
1;1;100.2;2022-07-28 07:00:00
----

== Задание

1. Спроектировать БД Postgres `payments`
2. Создать сервис `Payment` реализовать эндпоинт для приёма запросов
3. Реализовать очередь обмена сообщениями между сервисами
4. Наполнить БД Postgres `payments` транзакциями из запросов
5. Наполнить файл `transaction.csv` транзакциями из запросов

== Технологии

* Java 11+ / Kotlin 1.3+
* Spring Boot 2+
* Postgres 9.6+
* Любой брокер очередей
